name: CI

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing"

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building"

  deploy:
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"
